# Generated by Django 2.0.7 on 2019-07-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190705_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_img',
            field=models.CharField(default='/static/image/791e1a3aff021817b4028b1d91b92f80.jpeg', max_length=500, verbose_name='用户头像'),
        ),
    ]
