# Generated by Django 2.0.7 on 2019-08-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.CharField(default='/static/image/9ee0cde4dffa4fc780401561ed9d8809.jpeg', max_length=500, verbose_name='用户头像'),
        ),
    ]
