# Generated by Django 2.0.7 on 2019-08-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190814_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='11111111111', max_length=50, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.CharField(default='/static/image/791e1a3aff021817b4028b1d91b92f80.jpeg', max_length=500, verbose_name='用户头像'),
        ),
    ]
