# Generated by Django 2.0.7 on 2019-08-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190814_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=50, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.CharField(default='/static/image/c0a054d72dddb1df0d22f0bd2956a112.jpeg', max_length=500, verbose_name='用户头像'),
        ),
    ]
