# Generated by Django 2.0.7 on 2019-09-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190814_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.CharField(default='/static/image/2096723084f0ad8784bedc58f039a293.jpeg', max_length=500, verbose_name='用户头像'),
        ),
    ]
