# Generated by Django 2.0.7 on 2019-09-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190905_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.CharField(default='/static/image/c0a054d72dddb1df0d22f0bd2956a112.jpeg', max_length=500, verbose_name='用户头像'),
        ),
    ]
