# Generated by Django 2.0.7 on 2019-09-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190905_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.CharField(default='/static/image/ca905f2d53a18949c18596c0feb606d5.jpeg', max_length=500, verbose_name='用户头像'),
        ),
    ]
