# Generated by Django 2.0.7 on 2019-09-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190905_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.CharField(default='/static/image/791e1a3aff021817b4028b1d91b92f80.jpeg', max_length=500, verbose_name='用户头像'),
        ),
    ]
