# Generated by Django 2.0.7 on 2019-07-22 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=20, verbose_name='问题名称')),
                ('content', models.TextField(verbose_name='提问正文')),
                ('start_time', models.DateTimeField(verbose_name='提问时间')),
                ('read', models.IntegerField(verbose_name='阅读数量')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
