# Generated by Django 2.0.7 on 2019-07-22 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章评论id')),
                ('comment_content', models.TextField(verbose_name='私信正文')),
                ('comment_time', models.DateTimeField(verbose_name='回复时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='文章外键关联')),
                ('from_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCommentReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章评论回复id')),
                ('reply_id', models.CharField(max_length=20, verbose_name='回复id，当reply_id存在时，相当于用户在回复对别人的回复')),
                ('comment_content', models.TextField(verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(verbose_name='回复时间')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.ArticleComment', verbose_name='评论id')),
                ('from_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='文章来源用户id', to=settings.AUTH_USER_MODEL, verbose_name='回复用户id')),
                ('to_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='文章目标用户id', to=settings.AUTH_USER_MODEL, verbose_name='目标用户id')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='问答回复id')),
                ('comment_content', models.TextField(verbose_name='私信正文')),
                ('comment_time', models.DateTimeField(verbose_name='回复时间')),
                ('from_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question', verbose_name='问答外键关联')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCommentReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='问答用户回复id')),
                ('reply_id', models.CharField(max_length=20, verbose_name='回复id，当reply_id存在时，相当于用户在回复对别人的回复')),
                ('comment_content', models.TextField(verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(verbose_name='回复时间')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.QuestionComment', verbose_name='评论id')),
                ('from_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='问答来源用户id', to=settings.AUTH_USER_MODEL, verbose_name='回复用户id')),
                ('to_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='问答目标用户id', to=settings.AUTH_USER_MODEL, verbose_name='目标用户id')),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户私信id')),
                ('comment_time', models.DateTimeField(verbose_name='私信时间')),
                ('comment_content', models.TextField(verbose_name='私信正文')),
                ('from_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='发送用户id', to=settings.AUTH_USER_MODEL, verbose_name='发送私信用户id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='目标用户id', to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
        ),
        migrations.CreateModel(
            name='UserCommentReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户私信回复id')),
                ('reply_id', models.CharField(max_length=20, verbose_name='回复id，当reply_id存在时，相当于用户在回复对别人的回复')),
                ('comment_content', models.TextField(verbose_name='私信正文')),
                ('comment_time', models.DateTimeField(verbose_name='回复时间')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.UserComment', verbose_name='评论id')),
                ('from_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='用户私信来源用户id', to=settings.AUTH_USER_MODEL, verbose_name='回复用户id')),
                ('to_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='用户私信目标用户id', to=settings.AUTH_USER_MODEL, verbose_name='目标用户id')),
            ],
        ),
    ]
