# Generated by Django 2.0.7 on 2019-09-05 09:21

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_examplemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='content',
            field=mdeditor.fields.MDTextField(default='111'),
        ),
    ]
